export const TOP_DOWNLOADS = [
    {name: 'the beaty of Nature ',
    rating:"5",
    price:300, discountPrice:200},
    {name: 'the beaty of Nature ',
    rating:"5",
    price:300, discountPrice:200 },
    {name: 'the beaty of Nature ',
    rating:"5",
    price:300, discountPrice:200 },
    {name: 'the beaty of Nature ',
    rating:"5",
    price:300, discountPrice:200 },
    {name: 'the beaty of Nature ',
    rating:"5",
    price:300, discountPrice:200 },
    {name: 'the beaty of Nature ',
    rating:"5",
    price:300, discountPrice:200 },
    {name: 'the beaty of Nature ',
    rating:"5",
    price:300, discountPrice:200 },
]